version: "3"
services:
  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - angular-cli-network
    deploy:
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    ports:
      - 80:80
    command: [nginx-debug, '-g', 'daemon off;']
networks:
  angular-cli-network:
    external: true
