version: '2'
services:
    cassandra-node-one:
        image: cassandra:3.9
        volumes:
            - /var/db/simba-infra/cassandra-one/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
    cassandra-node-two:
        image: cassandra:3.9
	volumes:
            - /var/db/simba-infra/cassandra-two/:/var/lib/cassandra/data
        environment:
            - CASSANDRA_SEEDS=cassandra-node-one
