version: '2'
services:
    urvaraapm-cassandra:
        image: cassandra:3.9
        volumes:
            - /var/db/UrvaraApm/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
