version: '2'
services:
    minio1:
        image: minio/minio
        volumes:
           - minio_data1:/data
        ports:
            - 9001:9001
        environment:
            - MINIO_ACCESS_KEY=miniokey
            - MINIO_SECRET_KEY=miniosecret
        command: server /data
volumes:
  minio_data1:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: /var/new_db/minio/minioone/
