version: '3'
services:
    payment-app:
        image: payment:latest
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - EUREKA_CLIENT_SERVICE_URL_DEFAULTZONE=http://admin:$${jhipster.registry.password}@registry_jhipster-registry:8761/eureka
            - SPRING_CLOUD_CONFIG_URI=http://admin:$${jhipster.registry.password}@registry_jhipster-registry:8761/config
            - SPRING_DATA_CASSANDRA_CONTACTPOINTS=database_house-cassandra
            - JHIPSTER_REGISTRY_PASSWORD=admin
        networks:
            - jhipster-network
        deploy:
          replicas: 2
          update_config:
            parallelism: 1
            delay: 80s
          restart_policy:
            condition: on-failure
        ports:
            - 8081:8081
networks:
  jhipster-network:
    external: true
