version: '2'
services:
    cassandra-node-two:
        image: cassandra:3.9
        volumes: 
            - /var/db/Cassandra-Backup-two/cassandra/:/var/lib/cassandra/data
        ports:
            - 7000:7000
            - 7001:7001
            - 7199:7199
            - 9042:9042
            - 9160:9160
        environment:
            - CASSANDRA_SEEDS=192.168.43.78
            - CASSANDRA_BROADCAST_ADDRESS=192.168.43.184

