---
- name: Install Docker Compose
  hosts: dockerMachine
  gather_facts: False
  tasks:
 
     - name: Transfer the script
       copy: src=../docker-machine/install-docker-compose.sh dest=/home/docker mode=0777

     - name: Execute the script
       command: sh /home/docker/install-docker-compose.sh

     - name: Docker version installed
       command: docker-compose -v 
       register: docker-compose

     - debug: var=docker-compose.stdout_lines

     - debug:
         msg: Docker Compose Installation was Successful
