version: '3.1'
services:
  postgres-server:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
      PG_DATA: /var/lib/postgresql/data/pgdata
  
  zabbix-server:
    image: zabbix/zabbix-server-pgsql:ubuntu-latest
    restart: always
    environment:
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    ports: 
      - 10051:10051  
    depends_on:
      - postgres-server

  zabbix-web:
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-latest
    restart: always
    environment:
      ZBX_SERVER_HOST: zabbix-server
      ZBX_POSTMAXSIZE: 64M
      PHP_TZ: "Asia/Kolkata"
      POSTGRES_USER: zabbix
      POSTGRES_PASSWORD: zabbix
      POSTGRES_DB: zabbix
    depends_on:
      - postgres-server
      - zabbix-server
    ports:
      - 8090:80

  zabbix-agent:
    image: zabbix/zabbix-agent:latest
    privileged: true
    network_mode: "host"
    restart: unless-stopped
    environment:
      - ZBX_HOSTNAME=zabbixHost
      - ZBX_SERVER_HOST=127.0.0.1
    ports:
      - 10050:10050
    depends_on:
      - zabbix-server    

  grafana-xxl:   #optional
    image: monitoringartist/grafana-xxl:latest
    ports:
      - 3000:3000

  adminer:    #optional
    image: adminer
    restart: always
    ports:
      - 9080:9080